Create table dbDataDwItau.itau.Base360 (
    IdBase int constraint PkBase primary key clustered,
	Data datetime,
	CodigoReferencia smallint,
	Carteira varchar(64),
	Produto varchar(64),
	SubProduto varchar(64),
	Cluster varchar(4),
	IdDevedor int ,
	CnpjCpf varchar(14),
	IdTitulo int,
	NumeroContrato varchar(32),
	RazaoSocialNome varchar(128),
	Plano smallint,
	NumeroParcela smallint,
	DataInclusao datetime,
	DataVencimento datetime,
	DiasEmAtraso int,
	FaixaAtraso varchar(32),
	Risco money,
	SaldoVencido money,
	ValorRegularizacao money,
	AreaNegocio varchar(2),
	FaixaValor varchar(32),
	IdRetirada int,
);