Create table misitau.dbo.Base (
    CodigoReferencia smallint,
    Carteira varchar(64),
    Produto varchar(64),
    Cluster varchar(4),
    IdDevedor int,
    CnpjCpf varchar(14),
    IdTitulo int,
    NumeroContrato varchar(32),
    RazaoSocialNome varchar(128),
    Plano smallint,
    NumeroParcela smallint,
    DataInclusao datetime,
    DataVencimento datetime,
    Risco money,
    SaldoVencido money,
    ValorRegularizacao money,
    AreaNegocio varchar(2),
    Constraint PkBase primary key (IdDevedor, IdTitulo)
);