Create table misitau.dbo.Titulos (
	IdTitulo int constraint PkTitulos primary key clustered,
	IdEmpresa tinyint,
	IdDevedor int,
	IdCarteira smallint,
	IdProduto smallint,
	IdOrigem tinyint,
	NumeroContrato varchar(32),
	Plano smallint,
	PercentualJurosRemuneratorios float,
	DataInclusao datetime,
	IdUsuarioInclusao int,
	DataAtualizacao	datetime,
	IdUsuarioAtualizacao int,
	DataExclusao datetime,
	IdUsuarioExclusao int,
	ValidoDe datetime,
	ValidoAte datetime,
);